"""Initial schema

Revision ID: 27f0d193f12d
Revises: 
Create Date: 2025-11-23 11:18:25.127449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f0d193f12d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('chunks_stored', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('text_preview', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resume_session_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scholarship_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('matchmaker_results', sa.JSON(), nullable=True),
    sa.Column('essay_draft', sa.Text(), nullable=True),
    sa.Column('resume_optimizations', sa.JSON(), nullable=True),
    sa.Column('optimized_resume_markdown', sa.Text(), nullable=True),
    sa.Column('strategy_note', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=True),
    sa.Column('scholarship_intelligence', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('state_checkpoint', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['resume_session_id'], ['resume_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_session_id', sa.String(), nullable=False),
    sa.Column('resume_session_id', sa.String(), nullable=False),
    sa.Column('scholarship_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('had_interview', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_session_id'], ['resume_sessions.id'], ),
    sa.ForeignKeyConstraint(['workflow_session_id'], ['workflow_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_session_id', sa.String(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('weighted_keywords', sa.JSON(), nullable=False),
    sa.Column('gap_confidences', sa.JSON(), nullable=False),
    sa.Column('prioritized_gaps', sa.JSON(), nullable=False),
    sa.Column('current_target', sa.String(), nullable=True),
    sa.Column('conversation_history', sa.JSON(), nullable=True),
    sa.Column('collected_evidence', sa.JSON(), nullable=True),
    sa.Column('bridge_story', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_session_id'], ['workflow_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_sessions')
    op.drop_table('applications')
    op.drop_table('workflow_sessions')
    op.drop_table('resume_sessions')
    # ### end Alembic commands ###
